version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
    - nodejs
    - npm
  post_build:	
    - echo "Command run at 'post_build' step"
    - echo `date`
    - npm install
    - npm run build:examples