import React from 'react';
import { tableFromIPC } from 'apache-arrow';
import { arrowUtils, Components } from 'df_cereal';

/*
  df = pd.DataFrame({'a':[10,530], 'c': [-3.5, 9.7], 'd': [1,2]})

table = pa.Table.from_pandas(df)
feather.write_feather(table, "simple_df.feath", compression='uncompressed')
feath_text = open("simple_df.feath", "rb").read()
usable_feath_text = base64.b64encode(feath_text).decode('utf8')
*/
const base64table = [
 'QVJST1cxAAD/////gAMAABAAAAAAAAoADgAGAAUACAAKAAAAAAEEABAAAAAAAAoADAAAAA',
 'QACAAKAAAAqAIAAAQAAAABAAAADAAAAAgADAAEAAgACAAAAIACAAAEAAAAcAIAAHsiaW5k',
 'ZXhfY29sdW1ucyI6IFt7ImtpbmQiOiAicmFuZ2UiLCAibmFtZSI6IG51bGwsICJzdGFydC',
 'I6IDAsICJzdG9wIjogMiwgInN0ZXAiOiAxfV0sICJjb2x1bW5faW5kZXhlcyI6IFt7Im5h',
 'bWUiOiBudWxsLCAiZmllbGRfbmFtZSI6IG51bGwsICJwYW5kYXNfdHlwZSI6ICJ1bmljb2',
 'RlIiwgIm51bXB5X3R5cGUiOiAib2JqZWN0IiwgIm1ldGFkYXRhIjogeyJlbmNvZGluZyI6',
 'ICJVVEYtOCJ9fV0sICJjb2x1bW5zIjogW3sibmFtZSI6ICJhIiwgImZpZWxkX25hbWUiOi',
 'AiYSIsICJwYW5kYXNfdHlwZSI6ICJpbnQ2NCIsICJudW1weV90eXBlIjogImludDY0Iiwg',
 'Im1ldGFkYXRhIjogbnVsbH0sIHsibmFtZSI6ICJjIiwgImZpZWxkX25hbWUiOiAiYyIsIC',
 'JwYW5kYXNfdHlwZSI6ICJmbG9hdDY0IiwgIm51bXB5X3R5cGUiOiAiZmxvYXQ2NCIsICJt',
 'ZXRhZGF0YSI6IG51bGx9LCB7Im5hbWUiOiAiZCIsICJmaWVsZF9uYW1lIjogImQiLCAicG',
 'FuZGFzX3R5cGUiOiAiaW50NjQiLCAibnVtcHlfdHlwZSI6ICJpbnQ2NCIsICJtZXRhZGF0',
 'YSI6IG51bGx9XSwgImNyZWF0b3IiOiB7ImxpYnJhcnkiOiAicHlhcnJvdyIsICJ2ZXJzaW',
 '9uIjogIjE0LjAuMiJ9LCAicGFuZGFzX3ZlcnNpb24iOiAiMi4wLjMifQAAAAAGAAAAcGFu',
 'ZGFzAAADAAAAdAAAADQAAAAEAAAAqP///wAAAQIQAAAAFAAAAAQAAAAAAAAAAQAAAGQAAA',
 'CY////AAAAAUAAAADU////AAABAxAAAAAYAAAABAAAAAAAAAABAAAAYwAGAAgABgAGAAAA',
 'AAACABAAFAAIAAYABwAMAAAAEAAQAAAAAAABAhAAAAAcAAAABAAAAAAAAAABAAAAYQAAAA',
 'gADAAIAAcACAAAAAAAAAFAAAAA/////+gAAAAUAAAAAAAAAAwAFgAGAAUACAAMAAwAAAAA',
 'AwQAGAAAADAAAAAAAAAAAAAKABgADAAEAAgACgAAAHwAAAAQAAAAAgAAAAAAAAAAAAAABg',
 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAA',
 'AAAAAAAAEAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAQAAAAAAAAAAAAAAADAA',
 'AAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAACgAA',
 'AAAAAAASAgAAAAAAAAAAAAAAAAzAZmZmZmZmI0ABAAAAAAAAAAIAAAAAAAAA/////wAAAA',
 'AQAAAADAAUAAYACAAMABAADAAAAAAABABAAAAAKAAAAAQAAAABAAAAkAMAAAAAAADwAAAA',
 'AAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAwAAAAEAAgACgAAAKgCAAAEAAAAAQAAAA',
 'wAAAAIAAwABAAIAAgAAACAAgAABAAAAHACAAB7ImluZGV4X2NvbHVtbnMiOiBbeyJraW5k',
 'IjogInJhbmdlIiwgIm5hbWUiOiBudWxsLCAic3RhcnQiOiAwLCAic3RvcCI6IDIsICJzdG',
 'VwIjogMX1dLCAiY29sdW1uX2luZGV4ZXMiOiBbeyJuYW1lIjogbnVsbCwgImZpZWxkX25h',
 'bWUiOiBudWxsLCAicGFuZGFzX3R5cGUiOiAidW5pY29kZSIsICJudW1weV90eXBlIjogIm',
 '9iamVjdCIsICJtZXRhZGF0YSI6IHsiZW5jb2RpbmciOiAiVVRGLTgifX1dLCAiY29sdW1u',
 'cyI6IFt7Im5hbWUiOiAiYSIsICJmaWVsZF9uYW1lIjogImEiLCAicGFuZGFzX3R5cGUiOi',
 'AiaW50NjQiLCAibnVtcHlfdHlwZSI6ICJpbnQ2NCIsICJtZXRhZGF0YSI6IG51bGx9LCB7',
 'Im5hbWUiOiAiYyIsICJmaWVsZF9uYW1lIjogImMiLCAicGFuZGFzX3R5cGUiOiAiZmxvYX',
 'Q2NCIsICJudW1weV90eXBlIjogImZsb2F0NjQiLCAibWV0YWRhdGEiOiBudWxsfSwgeyJu',
 'YW1lIjogImQiLCAiZmllbGRfbmFtZSI6ICJkIiwgInBhbmRhc190eXBlIjogImludDY0Ii',
 'wgIm51bXB5X3R5cGUiOiAiaW50NjQiLCAibWV0YWRhdGEiOiBudWxsfV0sICJjcmVhdG9y',
 'IjogeyJsaWJyYXJ5IjogInB5YXJyb3ciLCAidmVyc2lvbiI6ICIxNC4wLjIifSwgInBhbm',
 'Rhc192ZXJzaW9uIjogIjIuMC4zIn0AAAAABgAAAHBhbmRhcwAAAwAAAHQAAAA0AAAABAAA',
 'AKj///8AAAECEAAAABQAAAAEAAAAAAAAAAEAAABkAAAAmP///wAAAAFAAAAA1P///wAAAQ',
 'MQAAAAGAAAAAQAAAAAAAAAAQAAAGMABgAIAAYABgAAAAAAAgAQABQACAAGAAcADAAAABAA',
 'EAAAAAAAAQIQAAAAHAAAAAQAAAAAAAAAAQAAAGEAAAAIAAwACAAHAAgAAAAAAAABQAAAAL',
 'ADAABBUlJPVzE='].join('')


/*
f1 = t2.schema.fields[0]
f1.type 
b = t2.batches[0]

b.schema.metadata // pandas index info
bi  = b.data.children[0].values[0]

*/

export default function() {
    // this test verifies that we can load  base64 into an array data and display the same table

    const b64bytes = arrowUtils.base64ToBytes(base64table)
  const t2 = tableFromIPC(b64bytes);
  console.log(t2);
    const dfd2 = arrowUtils.arrowToDFDataProxy(t2);    
    return <div><Components.SimpleDFWidget df_data={dfd2}/></div>
}
