import React from 'react';
import { tableFromIPC } from 'apache-arrow';
import { arrowUtils, Components } from 'df_cereal';

/*
ab = B64Viewer(pd.DataFrame({'a': [1, None, np.nan, np.inf, np.inf * -1]}))

*/
const base64Table = [
  'QVJST1cxAAD/////UAIAABAAAAAAAAoADgAGAAUACAAKAAAAAAEEABAAAAAAAAoADAAAAA',
'QACAAKAAAA4AEAAAQAAAABAAAADAAAAAgADAAEAAgACAAAALgBAAAEAAAAqgEAAHsiaW5k',
'ZXhfY29sdW1ucyI6IFt7ImtpbmQiOiAicmFuZ2UiLCAibmFtZSI6IG51bGwsICJzdGFydC',
'I6IDAsICJzdG9wIjogNSwgInN0ZXAiOiAxfV0sICJjb2x1bW5faW5kZXhlcyI6IFt7Im5h',
'bWUiOiBudWxsLCAiZmllbGRfbmFtZSI6IG51bGwsICJwYW5kYXNfdHlwZSI6ICJ1bmljb2',
'RlIiwgIm51bXB5X3R5cGUiOiAib2JqZWN0IiwgIm1ldGFkYXRhIjogeyJlbmNvZGluZyI6',
'ICJVVEYtOCJ9fV0sICJjb2x1bW5zIjogW3sibmFtZSI6ICJhIiwgImZpZWxkX25hbWUiOi',
'AiYSIsICJwYW5kYXNfdHlwZSI6ICJmbG9hdDY0IiwgIm51bXB5X3R5cGUiOiAiZmxvYXQ2',
'NCIsICJtZXRhZGF0YSI6IG51bGx9XSwgImNyZWF0b3IiOiB7ImxpYnJhcnkiOiAicHlhcn',
'JvdyIsICJ2ZXJzaW9uIjogIjE0LjAuMiJ9LCAicGFuZGFzX3ZlcnNpb24iOiAiMi4wLjMi',
'fQAABgAAAHBhbmRhcwAAAQAAABQAAAAQABQACAAGAAcADAAAABAAEAAAAAAAAQMQAAAAGA',
'AAAAQAAAAAAAAAAQAAAGEABgAIAAYABgAAAAAAAgD/////iAAAABQAAAAAAAAADAAWAAYA',
'BQAIAAwADAAAAAADBAAYAAAAMAAAAAAAAAAAAAoAGAAMAAQACAAKAAAAPAAAABAAAAAFAA',
'AAAAAAAAAAAAACAAAAAAAAAAAAAAABAAAAAAAAAAgAAAAAAAAAKAAAAAAAAAAAAAAAAQAA',
'AAUAAAAAAAAAAgAAAAAAAAAZAAAAAAAAAAAAAAAAAPA/AAAAAAAA+H8AAAAAAAD4fwAAAA',
'AAAPB/AAAAAAAA8P//////AAAAABAAAAAMABQABgAIAAwAEAAMAAAAAAAEAEAAAAAoAAAA',
'BAAAAAEAAABgAgAAAAAAAJAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoADAAAAA',
'QACAAKAAAA4AEAAAQAAAABAAAADAAAAAgADAAEAAgACAAAALgBAAAEAAAAqgEAAHsiaW5k',
'ZXhfY29sdW1ucyI6IFt7ImtpbmQiOiAicmFuZ2UiLCAibmFtZSI6IG51bGwsICJzdGFydC',
'I6IDAsICJzdG9wIjogNSwgInN0ZXAiOiAxfV0sICJjb2x1bW5faW5kZXhlcyI6IFt7Im5h',
'bWUiOiBudWxsLCAiZmllbGRfbmFtZSI6IG51bGwsICJwYW5kYXNfdHlwZSI6ICJ1bmljb2',
'RlIiwgIm51bXB5X3R5cGUiOiAib2JqZWN0IiwgIm1ldGFkYXRhIjogeyJlbmNvZGluZyI6',
'ICJVVEYtOCJ9fV0sICJjb2x1bW5zIjogW3sibmFtZSI6ICJhIiwgImZpZWxkX25hbWUiOi',
'AiYSIsICJwYW5kYXNfdHlwZSI6ICJmbG9hdDY0IiwgIm51bXB5X3R5cGUiOiAiZmxvYXQ2',
'NCIsICJtZXRhZGF0YSI6IG51bGx9XSwgImNyZWF0b3IiOiB7ImxpYnJhcnkiOiAicHlhcn',
'JvdyIsICJ2ZXJzaW9uIjogIjE0LjAuMiJ9LCAicGFuZGFzX3ZlcnNpb24iOiAiMi4wLjMi',
'fQAABgAAAHBhbmRhcwAAAQAAABQAAAAQABQACAAGAAcADAAAABAAEAAAAAAAAQMQAAAAGA',
'AAAAQAAAAAAAAAAQAAAGEABgAIAAYABgAAAAAAAgCAAgAAQVJST1cx'].join('')


export default function() {
    // this test verifies that we can load  base64 into an array data and display the same table

    const b64bytes = arrowUtils.base64ToBytes(base64Table)
  const t2 = tableFromIPC(b64bytes);
  console.log(t2);
    const dfd2 = arrowUtils.arrowToDFDataProxy(t2);    
    return <div><Components.SimpleDFWidget df_data={dfd2}/></div>
}
